version: '3.8'

services:
  db:
    restart: on-failure
    image: postgres:16-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command:
      sh -c "alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    restart: on-failure
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A video_analysis.tasks:celery_instance worker --loglevel=info -P threads
    depends_on:
      - backend
      - redis
      - db
    restart: on-failure

  volumes:
    postgres_data:
