"""Update DetectionResults model

Revision ID: 5491b9cc0dcd
Revises: c27ef6412909
Create Date: 2024-01-26 17:33:12.921191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5491b9cc0dcd'
down_revision: Union[str, None] = 'c27ef6412909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE detection_results ALTER COLUMN task_id TYPE UUID USING task_id::uuid')
    op.drop_column('detection_results', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('detection_results', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
